---
- hosts: webservers 
  become: yes
  tasks:

  - name: updating the packages
    yum:
      name: '*'
      state: latest 
    when: ansible_os_family == "RedHat"

  - name: updating packages in debian
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: installing apache in redhat
    yum:
      name: "{{ package_name }}"
      state: present
    notify: 
    - Restart Httpd
    when: ansible_os_family == "RedHat"

  - name: installing apache2 in debian
    apt:
      name: "{{ package_name }}"
      state: present
    notify: 
    - Restart apache
    when: ansible_os_family == "Debian"
  - name: backup homepage
    command: cp -n {{ homepage }} {{ backup }}

  - name: setting homepage
    copy:
     content: "hai frnds how are you welcome to the new page"
     dest: "{{ homepage }}"


  handlers:
  - name: Restart apache
    service:
      name: "{{ package_name }}"
      state: restarted


  handlers:
  - name: Restart httpd
    service:
      name: "{{ package_name }}"
      state: restarted

