---
- hosts: ip
  become: yes
  tasks: 
    - name: updating packages
      apt:
        update_cache: yes
    - name: inastalling nginix
      apt:
        name: nginx   
        state: present
    - name: restarting nginix
      apt: 
        name: nginx
        state: present
