---
- hosts: ubuntu
  vars: 
    package: tomcat7
    state: present
    maxmem: 512m
    maxpermsize: 256m
    multi packages:
      - tomcat7-docs
      - tomcat7-admin
      - tomcat7-examples
    tomcatuser: tom
    usrpasswd: tom
    role: role  
  become: yes
  tasks:
  - name: updating packages
    apt:
      update_cache: yes
  - name: installing tomcat    
    apt:
      name: "{{ package }}"
      state: "{{ state }}"
  - name: change default settings
    template:
      src: tomcat7.j2
      dest: /etc/default/tomcat7
    notify: 
      - restart tomcat7

  - name: change default settings
    template:
      src: tomcat.user.xml.j2
      dest: /etc/default/tomcat.user.xml
    notify: 
      - restart tomcat7

  - name: installing multiple packages
      apt: 
        name: "{{ item }}"
        state: present
      with_items: "{{ multi packages }}

  handlers:
  - name: restart tomcat7
    service: 
      name: "{{ package }}"
      state: restarted
    when: state == "present"     



